inherit_gem: { rubocop-rails-omakase: rubocop.yml }

require:
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  Exclude:
    - 'config/**/*'
    - 'spec/**/*'
    - 'db/migrate/**/*'
    - 'db/schema.rb'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'

RSpec/IncludeExamples:
  Enabled: true

RSpec/LeakyLocalVariable:
  Enabled: true

RSpec/Output:
  Enabled: true